# CluelyGuard Configuration
# Industrial-grade Linux Anti-LLM Proctoring System

# Application settings
app:
  name: "CluelyGuard"
  version: "0.1.0"
  environment: "production"  # development, staging, production
  teacher_pc_port: 8000
  log_level: "info"  # trace, debug, info, warn, error

# Database configuration removed - using file-based logging instead

# Web API settings
web:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["*"]

# Monitoring settings
monitoring:
  # Real-time BAM detection
  bam:
    enabled: true
    check_interval_seconds: 5
    typing_sample_size: 100
    anomaly_threshold: 0.7
    model_path: "bam_model.joblib"
  
  # Process monitoring
  process:
    enabled: true
    scan_interval_seconds: 30
    suspicious_binaries:
      # Known AI chat tools
      - "chatgpt"
      - "claude"
      - "bard"
      - "gpt"
      - "openai"
      - "anthropic"
      - "copilot"
      - "github-copilot"
      - "tabnine"
      - "kite"
      - "intellicode"
      - "codeium"
      
      # AI assistants and helpers
      - "assistant"
      - "ai-assistant"
      - "ai-helper"
      - "bot"
      - "ai-bot"
      
      # Voice and speech tools
      - "whisper"
      - "speech-to-text"
      - "voice-to-text"
      - "dictation"
      - "transcription"
      
      # Development AI tools
      - "cursor"
      - "replit"
      - "codespaces"
      - "gitpod"
      - "stackblitz"
      
      # Custom/stealth tools (from original config)
      - "cluely"
      - "cluely.bin"
      - "stealth_assistant"
  
  # Audio monitoring
  audio:
    enabled: true
    check_interval_seconds: 10
    pulse_audio_timeout_ms: 1000

  browser:
    enabled: true
    suspicious_keywords:
      - "chatgpt"
      - "copilot"
      - "claude"
      - "bard"
      - "openai"
      - "gpt"
      - "anthropic"
      - "llm"
    extension_paths:
      - "~/.config/google-chrome/Default/Extensions"
      - "~/.config/chromium/Default/Extensions"
      - "~/.mozilla/firefox/*.default-release/extensions"
      - "~/.mozilla/firefox/*.default/extensions"
      - "~/.config/BraveSoftware/Brave-Browser/Default/Extensions"
      - "~/.config/brave/Extensions"
      - "~/.local/share/brave/Brave-Browser/Default/Extensions"
      - "~/snap/brave/current/.config/BraveSoftware/Brave-Browser/Default/Extensions"

  file_system:
    enabled: true
    suspicious_extensions:
      - ".gguf"
      - ".bin"
      - ".pt"
      - ".pth"
      - ".safetensors"
      - ".pkl"
      - ".h5"
      - ".onnx"
      - ".tflite"
      - ".pb"
      - ".model"
      - ".weights"
    ai_model_paths:
      - "~/.cache/huggingface"
      - "~/.ollama"
      - "~/llamacpp"
      - "~/.cache/torch"
      - "~/.transformers"
      - "~/.local/share/oobabooga"
      - "~/text-generation-webui"
      - "~/.cache/gpt4all"
    monitoring_paths:
      - "/tmp"
      - "~/Downloads"
      - "~/Documents"
      - "~/.local/share"
      - "~/.cache"
      - "/var/tmp"
    large_file_threshold_mb: 100

  network:
    enabled: true
    suspicious_llm_domains:
      - "openai.com"
      - "anthropic.com"
      - "perplexity.ai"
      - "cohere.ai"
      - "huggingface.co"
      - "deepmind.com"
      - "nvidia.com"
      - "replicate.com"
      - "ai.google.com"
      - "aws.amazon.com"
      - "azure.microsoft.com"
      - "cloud.google.com"

  output_analysis:
    enabled: true
    perplexity_threshold: 0.7
    burstiness_threshold: 0.3
    keyword_threshold: 0.15
    suspicious_phrases:
      - "as an AI"
      - "language model"
      - "training data"
      - "knowledge cutoff"
      - "I don't have personal"
      - "I cannot browse"
      - "I cannot access"
      - "my last update"
      - "based on my training"

  screensharing:
    enabled: true
    known_screen_apps:
      - "obs"
      - "obs-studio"
      - "ffmpeg"
      - "wf-recorder"
      - "gstreamer"
      - "cheese"
      - "guvcview"
      - "kazam"
      - "recordmydesktop"
      - "simplescreenrecorder"
      - "zoom"
      - "skype"
      - "teams"
      - "discord"
      - "slack"
      - "google-chrome"
      - "firefox"
      - "chromium"
      - "x11vnc"
      - "vino"
      - "remmina"
      - "xrdp"
      - "teamviewer"
      - "anydesk"

  syscall:
    enabled: true
    ai_patterns:
      - name: "GPU_Computing"
        syscalls: ["openat", "ioctl", "mmap", "write", "read"]
        confidence: 0.7
        description: "Pattern indicating GPU computation usage"
      - name: "AI_Model_Loading"
        syscalls: ["openat", "fstat", "mmap", "madvise", "brk"]
        confidence: 0.8
        description: "Pattern for loading large AI model files"
      - name: "Network_AI_API"
        syscalls: ["socket", "connect", "sendto", "recvfrom", "write", "read"]
        confidence: 0.6
        description: "Pattern for AI API communication"
      - name: "Large_Memory_Operations"
        syscalls: ["mmap", "munmap", "mprotect", "madvise", "brk"]
        confidence: 0.5
        description: "Pattern for large memory operations typical of AI workloads"
      - name: "Python_AI_Execution"
        syscalls: ["execve", "openat", "stat", "access", "write"]
        confidence: 0.7
        description: "Pattern for Python-based AI tool execution"

  user_activity:
    enabled: true
    suspicious_clipboard_content:
      - "api_key"
      - "openai"
      - "anthropic"
      - "chatgpt"
      - "claude"
      - "gpt-"
      - "sk-"
      - "Bearer "
      - "Authorization:"
      - "prompt:"
      - "system:"
      - "assistant:"
      - "human:"
    suspicious_commands:
      - "pip install openai"
      - "pip install anthropic"
      - "pip install transformers"
      - "pip install torch"
      - "git clone"
      - "curl -X POST"
      - "wget"
      - "ollama"
      - "llamacpp"
      - "gpt4all"
      - "conda install"

  correlation:
    enabled: true
    correlation_window_seconds: 60
    min_confidence_for_alert: 0.75

  ram_dump:
    enabled: true
    interval_seconds: 300  # 5 minutes
    auto_dump_on_suspicion: true
    max_dumps_per_session: 10

# Alerting configuration
alerts:
  enabled: true
  webhook_url: null  # Set to your webhook URL if needed
  email:
    smtp_server: "localhost"
    smtp_port: 587
    username: ""
    password: ""
    recipients: []
  
  # Alert thresholds
  thresholds:
    bam_anomaly_score: 0.8
    suspicious_process_count: 1
    mic_usage_duration_seconds: 30

# Security settings
security:
  api_key_required: false
  jwt_secret: "your-secret-key-here"
  session_timeout_minutes: 60
  rate_limit:
    requests_per_minute: 100
    burst_size: 10

# Storage settings
storage:
  logs_dir: "logs"
  data_dir: "data"
  max_log_size_mb: 100
  log_retention_days: 30
  ram_dump_retention_days: 7

# Integration settings
integrations:
  # External monitoring systems
  prometheus:
    enabled: false
    port: 9090
  
  # SIEM integration
  siem:
    enabled: false
    endpoint: ""
    api_key: ""
  
  # Cloud monitoring
  cloudwatch:
    enabled: false
    region: "us-east-1"
    log_group: "cluelyguard" 