# Example Custom Configuration for CluelyGuard
# Copy this to config/local.yaml and customize for your environment

# Application settings
app:
  name: "CluelyGuard"
  version: "0.1.0"
  environment: "production"
  log_level: "info"

# Database configuration
database:
  url: "sqlite:///var/lib/cluelyguard/cluelyguard.db"
  max_connections: 10
  timeout_seconds: 30

# Web API settings
web:
  enabled: true
  host: "127.0.0.1"
  port: 8080
  cors:
    allowed_origins: ["http://localhost:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["*"]

# Monitoring settings
monitoring:
  # Real-time BAM detection
  bam:
    enabled: true
    check_interval_seconds: 5
    typing_sample_size: 10
    anomaly_threshold: 0.7
    model_path: "bam/bam_model.joblib"
  
  # Process monitoring - CUSTOMIZE THIS SECTION
  process:
    enabled: true
    scan_interval_seconds: 30
    suspicious_binaries:
      # === AI CHAT TOOLS ===
      # Popular AI chat applications
      - "chatgpt"
      - "claude"
      - "bard"
      - "gpt"
      - "openai"
      - "anthropic"
      
      # === CODE ASSISTANTS ===
      # AI-powered coding tools
      - "copilot"
      - "github-copilot"
      - "tabnine"
      - "kite"
      - "intellicode"
      - "codeium"
      - "cursor"
      
      # === DEVELOPMENT ENVIRONMENTS ===
      # Online coding platforms with AI
      - "replit"
      - "codespaces"
      - "gitpod"
      - "stackblitz"
      
      # === VOICE & SPEECH TOOLS ===
      # Voice-to-text and transcription tools
      - "whisper"
      - "speech-to-text"
      - "voice-to-text"
      - "dictation"
      - "transcription"
      
      # === AI ASSISTANTS ===
      # General AI assistant applications
      - "assistant"
      - "ai-assistant"
      - "ai-helper"
      - "bot"
      - "ai-bot"
      
      # === CUSTOM TOOLS ===
      # Add your own custom AI tools here
      - "my-custom-ai-tool"
      - "stealth-assistant"
      - "homework-helper"
      
      # === BLOCKED APPLICATIONS ===
      # Other applications you want to block during exams
      - "discord"
      - "slack"
      - "telegram"
      - "whatsapp"
      - "messenger"
  
  # Audio monitoring
  audio:
    enabled: true
    check_interval_seconds: 10
    pulse_audio_timeout_ms: 5000

# Alerting configuration
alerts:
  enabled: true
  webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "${SMTP_PASSWORD}"
    recipients: ["teacher@school.edu", "admin@school.edu"]
  
  # Alert thresholds - ADJUST SENSITIVITY HERE
  thresholds:
    bam_anomaly_score: 0.8          # 80% confidence = alert (0.0-1.0)
    suspicious_process_count: 1     # Alert if any AI tool found
    mic_usage_duration_seconds: 30  # Alert if mic used for 30+ seconds

# Security settings
security:
  api_key_required: true
  jwt_secret: "${JWT_SECRET}"
  session_timeout_minutes: 60
  rate_limit:
    requests_per_minute: 100
    burst_size: 20

# Storage settings
storage:
  logs_dir: "/var/log/cluelyguard"
  data_dir: "/var/lib/cluelyguard"
  max_log_size_mb: 100
  log_retention_days: 30

# Integration settings
integrations:
  prometheus:
    enabled: false
    port: 9090
  
  siem:
    enabled: false
    endpoint: "https://your-siem.com/api/events"
    api_key: "${SIEM_API_KEY}"
  
  cloudwatch:
    enabled: false
    region: "us-east-1"
    log_group: "/aws/cluelyguard"

# === CUSTOMIZATION GUIDE ===
#
# 1. PROCESS MONITORING:
#    - Add/remove AI tools from suspicious_binaries list
#    - Adjust scan_interval_seconds for more/less frequent checks
#    - The system also uses built-in AI pattern detection
#
# 2. SENSITIVITY TUNING:
#    - Lower bam_anomaly_score for more sensitive detection
#    - Higher values reduce false positives but may miss some AI usage
#    - Adjust suspicious_process_count based on your tolerance
#
# 3. ALERTING:
#    - Configure webhook_url for Slack/Discord notifications
#    - Set up email alerts for immediate notification
#    - Use environment variables for sensitive data
#
# 4. ENVIRONMENT VARIABLES:
#    - SMTP_PASSWORD: Email password
#    - JWT_SECRET: Secret for API authentication
#    - SIEM_API_KEY: SIEM integration key
#
# Example usage:
# export SMTP_PASSWORD="your-email-password"
# export JWT_SECRET="your-secret-key"
# cluelyguard start --description "Math Exam" --user-id "student123" 